defmodule BanterWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :banter

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_banter_key",
    signing_salt: "9TJREFUq",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Gateway WebSocket for real-time events
  #
  # connect_info: [:peer_data] exposes the raw TCP peer address to
  # UserSocket.connect/3, used for rate limiting. NOTE: if this app is ever
  # deployed behind a reverse proxy/CDN, :peer_data will be the proxy's IP,
  # not the real client's — add :x_headers and parse x-forwarded-for then.
  socket "/gateway", BanterWeb.UserSocket,
    websocket: [connect_info: [:peer_data]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :banter,
    gzip: not code_reloading?,
    only: BanterWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serve uploaded files from "priv/static/uploads" directory
  plug Plug.Static,
    at: "/uploads",
    from: {:banter, "priv/static/uploads"},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :banter
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BanterWeb.Router
end
