defmodule Banter.Repo.Migrations.AddMissingFkIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:voice_states, [:server_id])

    create index(:voice_states, [:channel_id])

    create index(:servers, [:owner_id])

    create index(:messages, [:reply_to_id])

    create index(:messages, [:author_id])

    create index(:messages, [:channel_id, :id])

    create index(:members, [:server_id])

    create index(:channels, [:server_id])

    create index(:attachments, [:message_id])
  end

  def down do
    drop_if_exists index(:attachments, [:message_id])

    drop_if_exists index(:channels, [:server_id])

    drop_if_exists index(:members, [:server_id])

    drop_if_exists index(:messages, [:channel_id, :id])

    drop_if_exists index(:messages, [:author_id])

    drop_if_exists index(:messages, [:reply_to_id])

    drop_if_exists index(:servers, [:owner_id])

    drop_if_exists index(:voice_states, [:channel_id])

    drop_if_exists index(:voice_states, [:server_id])
  end
end
