defmodule Banter.Repo.Migrations.AddAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages_versions) do
      modify :content, :text, null: true
    end

    alter table(:messages) do
      modify :content, :text, null: true
    end

    create table(:attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :filename, :text, null: false
      add :size, :bigint, null: false
      add :content_type, :text, null: false
      add :storage_path, :text, null: false
      add :url, :text, null: false
      add :width, :bigint
      add :height, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :message_id,
          references(:messages,
            column: :id,
            name: "attachments_message_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint(:attachments, "attachments_message_id_fkey")

    drop table(:attachments)

    alter table(:messages) do
      modify :content, :text, null: false
    end

    alter table(:messages_versions) do
      modify :content, :text, null: false
    end
  end
end
