defmodule Banter.Repo.Migrations.AddChatResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:servers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :icon_url, :text
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:servers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:servers_versions) do
      modify :version_source_id,
             references(:servers,
               column: :id,
               name: "servers_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:servers) do
      add :name, :text, null: false
      add :description, :text
      add :icon_url, :text
      add :invite_code, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "servers_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:servers, [:invite_code], name: "servers_unique_invite_code_index")

    create table(:messages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :content, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:messages_versions) do
      modify :version_source_id,
             references(:messages,
               column: :id,
               name: "messages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:messages) do
      add :content, :text, null: false
      add :edited_at, :utc_datetime_usec
      add :pinned, :boolean, null: false, default: false
      add :message_type, :text, null: false, default: "default"

      add :reply_to_id,
          references(:messages,
            column: :id,
            name: "messages_reply_to_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :nonce, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id, :uuid, null: false
      add :author_id, :uuid
      add :archived_at, :utc_datetime_usec
    end

    create table(:members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :nickname, :text
      add :role, :text, null: false, default: "member"

      add :joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "members_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :server_id,
          references(:servers,
            column: :id,
            name: "members_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:members, [:user_id, :server_id],
             name: "members_unique_user_per_server_index"
           )

    create table(:channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:messages) do
      modify :channel_id,
             references(:channels,
               column: :id,
               name: "messages_channel_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "messages_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:channels) do
      add :name, :text, null: false
      add :type, :text, null: false, default: "text"
      add :topic, :text
      add :position, :bigint, null: false, default: 0
      add :slowmode_seconds, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :server_id,
          references(:servers,
            column: :id,
            name: "channels_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:channels, [:name, :server_id],
             name: "channels_unique_name_per_server_index"
           )
  end

  def down do
    drop_if_exists unique_index(:channels, [:name, :server_id],
                     name: "channels_unique_name_per_server_index"
                   )

    drop constraint(:channels, "channels_server_id_fkey")

    alter table(:channels) do
      remove :archived_at
      remove :server_id
      remove :updated_at
      remove :inserted_at
      remove :slowmode_seconds
      remove :position
      remove :topic
      remove :type
      remove :name
    end

    drop constraint(:messages, "messages_channel_id_fkey")

    drop constraint(:messages, "messages_author_id_fkey")

    alter table(:messages) do
      modify :author_id, :uuid
      modify :channel_id, :uuid
    end

    drop table(:channels)

    drop_if_exists unique_index(:members, [:user_id, :server_id],
                     name: "members_unique_user_per_server_index"
                   )

    drop constraint(:members, "members_user_id_fkey")

    drop constraint(:members, "members_server_id_fkey")

    drop table(:members)

    drop constraint(:messages, "messages_reply_to_id_fkey")

    alter table(:messages) do
      remove :archived_at
      remove :author_id
      remove :channel_id
      remove :updated_at
      remove :inserted_at
      remove :nonce
      remove :reply_to_id
      remove :message_type
      remove :pinned
      remove :edited_at
      remove :content
    end

    drop constraint(:messages_versions, "messages_versions_version_source_id_fkey")

    alter table(:messages_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:messages)

    drop table(:messages_versions)

    drop_if_exists unique_index(:servers, [:invite_code],
                     name: "servers_unique_invite_code_index"
                   )

    drop constraint(:servers, "servers_owner_id_fkey")

    alter table(:servers) do
      remove :archived_at
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :invite_code
      remove :icon_url
      remove :description
      remove :name
    end

    drop constraint(:servers_versions, "servers_versions_version_source_id_fkey")

    alter table(:servers_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:servers)

    drop table(:servers_versions)
  end
end
