defmodule Banter.Repo.Migrations.PartialUniqueChannelName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:channels, [:name, :server_id],
                     name: "channels_unique_name_per_server_index"
                   )

    create unique_index(:channels, [:name, :server_id],
             name: "channels_unique_name_per_server_index",
             where: "(archived_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:channels, [:name, :server_id],
                     name: "channels_unique_name_per_server_index"
                   )

    create unique_index(:channels, [:name, :server_id],
             name: "channels_unique_name_per_server_index"
           )
  end
end
