defmodule Banter.Repo.Migrations.AddVoiceStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:voice_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :self_mute, :boolean, null: false, default: false
      add :self_deaf, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "voice_states_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :channel_id,
          references(:channels,
            column: :id,
            name: "voice_states_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :server_id,
          references(:servers,
            column: :id,
            name: "voice_states_server_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:voice_states, [:user_id], name: "voice_states_unique_user_voice_index")
  end

  def down do
    drop_if_exists unique_index(:voice_states, [:user_id],
                     name: "voice_states_unique_user_voice_index"
                   )

    drop constraint(:voice_states, "voice_states_user_id_fkey")

    drop constraint(:voice_states, "voice_states_channel_id_fkey")

    drop constraint(:voice_states, "voice_states_server_id_fkey")

    drop table(:voice_states)
  end
end
